export const cities = {
    "A": ["Ahmedabad",
        "Alexandria",
        "Abidjan",
        "Ankara",
        "Addis Ababa",
        "Al Mawsil al Jadidah",
        "Al Basrah al Qadimah",
        "Almaty",
        "Algiers",
        "Accra",
        "Aleppo",
        "Asuncion",
        "Anshan",
        "Agra",
        "Antananarivo",
        "Amman",
        "Adana",
        "Abuja",
        "Adelaide",
        "Anyang",
        "Amritsar",
        "Allahabad",
        "Aurangabad",
        "Austin",
        "Abu Ghurayb",
        "Abobo",
        "Aba",
        "Ankang",
        "Ahvaz",
        "Arequipa",
        "Anqing",
        "Anshun",
        "Antalya",
        "Aligarh",
        "Amsterdam",
        "Ashgabat",
        "Alvaro Obregon",
        "As Sulaymaniyah",
        "Aguascalientes",
        "Ansan-si",
        "Agadir",
        "Acapulco de Juarez",
        "Athens",
        "Al Ahmadi",
        "Al Hudaydah",
        "Amravati",
        "Abu Dhabi",
        "Anyang-si",
        "Abeokuta",
        "Asmara",
        "Albuquerque",
        "Aden",
        "Antipolo",
        "Aksu",
        "Ajmer",
        "Azadshahr",
        "Aparecida de Goiania",
        "Asansol",
        "Arak",
        "Astrakhan",
        "Aracaju",
        "Ajman City",
        "Atlanta",
        "Antwerpen",
        "Amagasaki",
        "Ananindeua",
        "Al Mahallah al Kubra",
        "Akola",
        "Al Kharj",
        "Ado-Ekiti",
        "Akure",
        "Asyut",
        "Al Mansurah",
        "Auckland",
        "Azcapotzalco",
        "Ardabil",
        "Al Hoceima",
        "Arlington",
        "Abomey-Calavi",
        "Abadan",
        "Ahmadnagar",
        "Anqiu",
        "Al Qadarif",
        "Atasehir",
        "Aurora",
        "Asahikawa",
        "Arkhangel'sk",
        "Ambon",
        "Anaheim",
        "Arusha",
        "Ambattur",
        "Alicante",
        "Al 'Amarah",
        "Akita",
        "Anapolis",
        "Ad Diwaniyah",
        "Andijon",
        "Armenia",
        "Al Kut",
        "Antofagasta",
        "Al Fayyum",
        "Angeles City",
        "Anchorage",
        "Aomori",
        "Akashi",
        "Al Hufuf",
        "Al Mubarraz",
        "Al Hillah",
        "Adapazari",
        "Alto Barinas",
        "Alwar",
        "Ar Rayyan",
        "Aizawl",
        "Aachen",
        "Aktobe",
        "Aral",
        "Augsburg",
        "Altona",
        "Avadi",
        "A Coruna",
        "Angarsk",
        "Aswan",
        "Alappuzha",
        "Anantapur",
        "Arhus",
        "Al Jubayl",
        "Atani",
        "Al Minya",
        "Ashdod",
        "Atsugi",
        "Adiyaman",
        "Arrah",
        "Ageoshimo",
        "Amarnath",
        "Alor Setar",
        "Archway",
        "Abha",
        "Arroyo Naranjo",
        "Antakya",
        "Alvorada",
        "Arlington",
        "Annaba",
        "Alcala de Henares",
        "Agartala",
        "Atsiaman",
        "Al Khums",
        "Aurora",
        "Az Zawiyah",
        "Armavir",
        "Amol",
        "Amarillo",
        "Arnavutkoey",
        "Akron",
        "Aberdeen",
        "Americana",
        "Al Fallujah",
        "Altay",
        "Almeria",
        "Acarigua",
        "Antsirabe",
        "Ad-Damazin",
        "Arica",
        "Araure",
        "Anda",
        "Atyrau",
        "Amadora",
        "Anjo",
        "Ar Raqqah",
        "Almere Stad",
        "Amroha",
        "Aracatuba",
        "Albacete",
        "Arad",
        "Araraquara",
        "Angers",
        "Alcorcon",
        "Awka",
        "Abakan",
        "Arapiraca",
        "Adoni",
        "Aydin",
        "Anbu",
        "Anderlecht",
        "Ashikaga",
        "Admiralteisky",
        "Ambato",
        "Alandur",
        "Angra dos Reis",
        "Alexandria",
        "As Samawah",
        "Aksaray",
        "Astoria",
        "Arganzuela",
        "Arar",
        "Astanajapura",
        "As Salimiyah",
        "Aix-en-Provence",
        "Ambala",
        "Afyonkarahisar",
        "Acheng",
        "Ashkelon",
        "Amiens",
        "Arnhem",
        "Abbotsford",
        "Al'met'yevsk",
        "Ayacucho",
        "Amersfoort",
        "Anaco",
        "Anand",
        "Apeldoorn",
        "Ajdabiya",
        "Adiwerna",
        "Abakaliki",
        "Abiko",
        "Al Bab",
        "Abohar",
        "Al Ajaylat",
        "Acilia-Castel Fusano-Ostia Antica",
        "Andong",
        "Arish",
        "Al Manaqil",
        "Asaka",
        "Alhambra",
        "Amaigbo",
        "Angren",
        "Al Jadid",
        "Ampang",
        "Agadez",
        "Alagoinhas",
        "Az Zubayr",
        "Amherst",
        "Aalborg",
        "Abilene",
        "Alberton",
        "Allentown",
        "Abbottabad",
        "Ajax",
        "Ain Oussera",
        "Adilabad",
        "Achinsk",
        "Ann Arbor",
        "Athens",
        "Azamgarh",
        "Ahmadpur East",
        "Algeciras",
        "Alchevsk",
        "Anliu",
        "Arvada",
        "Alanya",
        "Apopa",
        "Ashoknagar Kalyangarh",
        "Araucaria",
        "Achalpur",
        "Atibaia",
        "Antioch",
        "Ambur",
        "Araruama",
        "Arzamas",
        "An Nuhud",
        "Atbara",
        "Alcobendas",
        "Araras",
        "As Suwayq",
        "Apucarana",
        "Al Hawamidiyah",
        "Anning",
        "Arjawinangun",
        "Ain Beida",
        "Azare",
        "Alto Hospicio",
        "Araguaina",
        "Al Faw",
        "Abengourou",
        "Akademicheskoe",
        "Amaravati",
        "Artem",
        "Al Jumayl",
        "Assis",
        "Argenteuil",
        "Abu Kabir",
        "Anyama",
        "Alamar",
        "Airoli",
        "Amreli",
        "Akhmim",
        "Al Matariyah",
        "Acharnes",
        "Apatzingan",
        "Alief",
        "Albany",
        "Akbarabad",
        "Andria",
        "Al Qatif",
        "Allen",
        "Asan",
        "Ariana",
        "Arapongas",
        "Al Muharraq",
        "Amalner",
        "Azimpur",
        "Araguari",
        "Aurangabad",
        "Aqaba",
        "As Salamiyah",
        "Alkmaar",
        "Ahar",
        "Al Harithah",
        "Arden-Arcade",
        "Agri",
        "Aligudarz",
        "Alvand",
        "Ancona",
        "Avignon",
        "Almirante Tamandare",
        "Ashiya",
        "Alaghsas",
        "Asheville",
        "Al Bahah",
        "Arayat",
        "Ath Thawrah",
        "Arifwala",
        "Alegrete",
        "Angono",
        "Ad Douiem",
        "Akot",
        "Asnieres-sur-Seine",
        "Atlixco",
        "Al Farwaniyah",
        "Al Fujairah City",
        "Apartado",
        "Anlong",
        "Alhambra",
        "Attock City",
        "Aruppukkottai",
        "Al Marj",
        "Amsterdam-Zuidoost",
        "Aflou",
        "Akhisar",
        "Ambarawa",
        "Anakapalle",
        "Al Fqih Ben Calah",
        "Ahwatukee Foothills",
        "Antsiranana",
        "Amasya",
        "Ash Shatrah",
        "Aoxi",
        "Algorta",
        "Araxa",
        "Anzhero-Sudzhensk",
        "Ashmun",
        "Anguo",
        "Abomey",
        "Azov",
        "Abreu e Lima",
        "Agboville",
        "Ar Rass",
        "Al Hasakah",
        "Avare",
        "Avondale",
        "Atakpame",
        "Aulnay-sous-Bois",
        "As Salt",
        "Anantnag",
        "Amstelveen",
        "Ar Rifa'",
        "Arakkonam",
        "Agulu",
        "Aviles",
        "Alameda",
        "Arona",
        "Al Hayy",
        "Alafaya",
        "Abaetetuba",
        "Alekseyevka",
        "Aalst",
        "Apalit",
        "Agua Prieta",
        "Amozoc de Mota",
        "Auburn",
        "Arraijan",
        "Arnsberg",
        "Antibes",
        "Arezzo",
        "Arlington Heights",
        "Azzaba",
        "Ar Ramtha",
        "Alvand",
        "Albany",
        "Aylesbury",
        "Ankleshwar",
        "Antonio Enes",
        "Al Bayda'",
        "Asbest",
        "Aramoko-Ekiti",
        "Abeche",
        "Appleton",
        "Ambajogai",
        "Aku",
        "Al Buraymi",
        "Asaba",
        "Aguachica",
        "Ambikapur",
        "Almelo",
        "Ain Touta",
        "Ash Shafa",
        "Apple Valley",
        "Aruja",
        "Afikpo",
        "Amatitlan",
        "Apomu",
        "Alfenas",
        "Agios Dimitrios",
        "Abu Tij",
        "Anlu",
        "Aubervilliers",
        "Altamira",
        "Alytus",
        "Antanifotsy",
        "Auraiya",
        "Alphen aan den Rijn",
        "Adler",
        "Alcala de Guadaira",
        "Ayvalik",
        "Aigaleo",
        "Abhar",
        "Arba Minch",
        "Arauca",
        "Anseong",
        "Abnub",
        "Aschaffenburg",
        "Ain Fakroun",
        "Al Qusiyah",
        "Al Jammaliyah",
        "Al Fahahil",
        "Altagracia de Orituco",
        "Attili",
        "Artemisa",
        "Ardesen",
        "Altamura",
        "Al Kharjah",
        "Arenella",
        "Agbor",
        "Atlantis",
        "Al Manzalah",
        "Araria",
        "Aalen",
        "Anjar",
        "Aleksin",
        "Ambovombe",
        "Akbou",
        "Aflao",
        "Algueirao",
        "Alba Iulia",
        "Atascocita",
        "Al Marsa",
        "Afgooye",
        "Alipur Duar",
        "Aquiraz",
        "Ames",
        "Adigrat",
        "Ashoknagar",
        "Ahlat",
        "Aksehir",
        "Alessandria",
        "Aleksandrov",
        "Awsim",
        "Al Fashn",
        "As Safirah",
        "Alpharetta",
        "Ain Sefra",
        "Auchi",
        "Arni",
        "Ashford",
        "Afragola",
        "Al Khankah",
        "Abepura",
        "Assen",
        "Auburn",
        "Angyalfoeld",
        "Adzope",
        "Al Qurayn",
        "Al Shamkhah City",
        "Alcoy",
        "Aldershot",
        "Asti",
        "Apatity",
        "Abu Qurqas",
        "Al Minshah",
        "Anuradhapura",
        "Asker",
        "Al Mithnab",
        "Arambagh",
        "Akim Oda",
        "Adelaide Hills",
        "Antony",
        "Agia Paraskevi",
        "Asadabad",
        "Altamira",
        "Azua",
        "Arrecife",
        "Abadeh",
        "As-Suwayda",
        "Antu",
        "Ardakan",
        "Attur",
        "Arsen'yev",
        "Arcadia",
        "Aracruz",
        "Ar Rumaythiyah",
        "Ariquemes",
        "Acambaro",
        "Anxiang",
        "Ash Shamiyah",
        "Albu Kamal",
        "Al Hindiyah",
        "Ain Temouchent",
        "Arcoverde",
        "Anamur",
        "Avila",
        "Ambalangoda",
        "Ankeny",
        "Asaka",
        "Al Qanatir al Khayriyah",
        "Ambilobe",
        "Arua",
        "At Tall",
        "Amuntai",
        "Aurora",
        "Anjiang",
        "Anan",
        "Abington",
        "Anderson",
        "Ahu",
        "Ahlen",
        "Abyek",
        "Abancay",
        "Al Ain City",
        "Anjangaon",
        "Al Khafji",
        "Asenovgrad",
        "Al Mayadin",
        "Ad Dawadimi",
        "Ajaccio",
        "Allapattah",
        "Aveiro",
        "Aranjuez",
        "Altuf'yevskiy",
        "Azul",
        "Acton",
        "Anapa",
        "Acerra",
        "Arles",
        "Ajodhya",
        "Ar Rastan",
        "Az Zulfi",
        "Alexandroupoli",
        "Aversa",
        "Adilcevaz",
        "Amalapuram",
        "Amora",
        "Albi",
        "Andradina",
        "Antratsyt",
        "Ain Defla",
        "Arandas",
        "Albany",
        "Albany Park",
        "Ar Riqqah",
        "Arcot",
        "At Tall al Kabir",
        "Amparafaravola",
        "Arganda",
        "Agustin Codazzi",
        "Apple Valley",
        "Acayucan",
        "Al Miqdadiyah",
        "Arjona",
        "Abu Road",
        "Al Khaburah",
        "Anju",
        "Aliso Viejo",
        "Aonla",
        "Al-Hamdaniya",
        "Akademgorodok",
        "Arashiyama"],

    "B": ["Boston",
        "Baltimore",
        "Bakersfield",
        "Buffalo",
        "Boise",
        "Baton Rouge",
        "Birmingham",
        "Brownsville",
        "Bayamon",
        "Bellevue",
        "Bridgeport",
        "Berkeley",
        "Brandon",
        "Beaumont",
        "Broken Arrow",
        "Billings",
        "Bend",
        "Boulder",
        "Boca Raton",
        "Burbank",
        "Beaverton",
        "Bellingham",
        "Brockton",
        "Buckeye",
        "Bryan",
        "Bloomington",
        "Bloomington",
        "Boynton Beach",
        "Buena Park",
        "Brooklyn Park",
        "Baytown",
        "Bowling Green",
        "Bethlehem",
        "Bloomington",
        "Bellflower",
        "Bismarck",
        "Baldwin Park",
        "Broomfield",
        "Bolingbrook",
        "Bossier City",
        "Blaine",
        "Brentwood",
        "Bonita Springs",
        "Bentonville",
        "Bayonne",
        "Bradenton",
        "Brentwood",
        "Bethesda",
        "Burnsville",
        "Brookhaven",
        "Bartlett",
        "Bristol",
        "Brookline",
        "Bowie",
        "Blue Springs",
        "Beaumont",
        "Burlington",
        "Bozeman",
        "Bellevue",
        "Berwyn",
        "Burleson",
        "Battle Creek",
        "Burien",
        "Bothell",
        "Beavercreek",
        "Bel Air South",
        "Bedford",
        "Biloxi",
        "Barnstable Town",
        "Bountiful",
        "Brighton",
        "Blacksburg",
        "Brentwood",
        "Binghamton",
        "Burlington",
        "Bremerton",
        "Burke",
        "Brea",
        "Bullhead City",
        "Beverly",
        "Bell Gardens",
        "Brookfield",
        "Bartlett",
        "Buffalo Grove",
        "Belleville",
        "Benton",
        "Bettendorf",
        "Braintree Town",
        "Beloit",
        "Brighton",
        "Bartlesville",
        "Bell",
        "Brunswick",
        "Buenaventura Lakes",
        "Butte",
        "Boardman",
        "Bluffton",
        "Beverly Hills",
        "Bangor",
        "Burlingame",
        "Bethel Park",
        "Bay City",
        "Bel Air North",
        "Bowling Green",
        "Banning",
        "Brooklyn Center",
        "Ballwin",
        "Bay Shore",
        "Big Spring",
        "Bixby",
        "Bella Vista",
        "Brownsburg",
        "Burton",
        "Bridgewater Town",
        "Benicia",
        "Burbank",
        "Burlington",
        "Bayonet Point",
        "Bristol",
        "Bergenfield",
        "Batavia",
        "Bainbridge Island",
        "Belmont",
        "Bethany",
        "Brawley",
        "Bessemer",
        "Belmont",
        "Bay Point",
        "Barberton",
        "Belvidere",
        "Baldwin",
        "Brandon",
        "Belton",
        "Bloomingdale",
        "Brookings",
        "Balch Springs",
        "Burlington",
        "Bailey's Crossroads",
        "Belton",
        "Barstow",
        "Bridgeton",
        "Benbrook",
        "Blue Island",
        "Brent",
        "Battle Ground",
        "Bryant",
        "Bloomington",
        "Birmingham",
        "Boerne",
        "Bluffdale",
        "Biddeford",
        "Bellview",
        "Bloomingdale",
        "Bonney Lake",
        "Brambleton",
        "Bothell West",
        "Ballenger Creek",
        "Bartow",
        "Bear",
        "Belle Glade",
        "Bayshore Gardens",
        "Brigham City",
        "Boone",
        "Bayou Cane",
        "Bourbonnais",
        "Baldwin",
        "Bellaire",
        "Bethany",
        "Badger",
        "Broadview Heights",
        "Blythe",
        "Brenham",
        "Berea",
        "Buda",
        "Bryn Mawr-Skyway",
        "Brushy Creek",
        "Bellwood",
        "Brownwood",
        "Bon Air",
        "Brook Park",
        "Burke Centre",
        "Brookfield",
        "Beltsville",
        "Buckhall",
        "Bethpage",
        "Bensenville",
        "Bay City",
        "Burlington",
        "Brownsville",
        "Braselton",
        "Bristol",
        "Boulder City",
        "Berea",
        "Buffalo",
        "Bull Run",
        "Buford",
        "Bostonia",
        "Beaver Dam",
        "Bellevue",
        "Brunswick",
        "Bridgeview",
        "Bemidji",
        "Bay St. Louis",
        "Belvedere Park",
        "Bradley",
        "Bellmore",
        "Berkley",
        "Beckley",
        "Beech Grove",
        "Brunswick",
        "Bay Village",
        "Brooklyn Park",
        "Bellair-Meadowbrook Terrace",
        "Berea",
        "Beacon",
        "Bradley Gardens",
        "Bridgetown",
        "Black Forest",
        "Batavia",
        "Belle Chasse",
        "Bloomsburg",
        "Brandermill",
        "Broussard",
        "Brecksville",
        "Beaufort",
        "Bexley",
        "Bardstown",
        "Broadlands",
        "Bellefontaine",
        "Big Bear City",
        "Beach Park",
        "Brainerd",
        "Brookside",
        "Bensville",
        "Bedford",
        "Beeville",
        "Belmont",
        "Baker",
        "Berthoud",
        "Blytheville",
        "Bonita",
        "Butler",
        "Blue Ash",
        "Blackfoot",
        "Beatrice",
        "Bedford",
        "Baraboo",
        "Boone",
        "Brock Hall",
        "Borger",
        "Branson",
        "Berkley",
        "Bainbridge",
        "Babylon",
        "Bucyrus",
        "Brookhaven",
        "Brown Deer",
        "Bernalillo",
        "Bothell East",
        "Big Lake",
        "Beachwood",
        "Beachwood",
        "Bridgeton",
        "Burkburnett",
        "Bayou Blue",
        "Bellmawr",
        "Broomall",
        "Bolivar",
        "Boonton",
        "Belgrade",
        "Bogalusa",
        "Browns Mills",
        "Batesville",
        "Burlington",
        "Byram",
        "Burley",
        "Bacliff",
        "Bellmead",
        "Burr Ridge",
        "Box Elder",
        "Bonham",
        "Brooklyn",
        "Bluffton",
        "Big Rapids",
        "Bel Air",
        "Bellefontaine Neighbors",
        "Brandon",
        "Bedford Heights",
        "Boulder Hill",
        "Beverly Hills",
        "Berlin",
        "Barrington",
        "Bethel",
        "Bull Mountain"],

    "C": ["Chengdu",
        "Cairo",
        "Chongqing",
        "Chennai",
        "Changchun",
        "Chattogram",
        "Cape Town",
        "Changzhou",
        "Casablanca",
        "Changsha",
        "Caracas",
        "Chicago",
        "Cali",
        "Coimbatore",
        "Camayenne",
        "Conakry",
        "Chaozhou",
        "Curitiba",
        "Changshu",
        "Caloocan City",
        "Cixi",
        "Changde",
        "Cordoba",
        "Ciudad Juarez",
        "Changzhi",
        "Copenhagen",
        "Ciudad Nezahualcoyotl",
        "Chelyabinsk",
        "Campinas",
        "Calgary",
        "Chandigarh",
        "Cartagena",
        "Ciudad Guayana",
        "Chiba",
        "Columbus",
        "Charlotte",
        "Cochabamba",
        "Chenzhou",
        "Callao",
        "Can Tho",
        "Chihuahua",
        "Cebu City",
        "Cankaya",
        "Chuzhou",
        "Cotonou",
        "Campo Grande",
        "Cucuta",
        "Changzhi",
        "Culiacan",
        "Cheonan",
        "Colombo",
        "Chisinau",
        "Cheongju-si",
        "Cancun",
        "Contagem",
        "Coyoacan",
        "Chizhou",
        "Cochin",
        "Cuttack",
        "Chiclayo",
        "Changwon",
        "Cuauhtemoc",
        "Cangzhou",
        "Cuiaba",
        "Cimahi",
        "Ciudad Lopez Mateos",
        "Cuautitlan Izcalli",
        "Ciudad Apodaca",
        "Calabar",
        "Colorado Springs",
        "Constantine",
        "Chengde",
        "Cardiff",
        "Cheboksary",
        "Cagayan de Oro",
        "Carrefour",
        "Ciudad Bolivar",
        "Cumana",
        "Chaoyang",
        "Comilla",
        "Cleveland",
        "Campos dos Goytacazes",
        "Chongzuo",
        "Caxias do Sul",
        "Canberra",
        "Christchurch",
        "Carapicuiba",
        "Coventry",
        "Ciudad General Escobedo",
        "Campina Grande",
        "Camaguey",
        "Chifeng",
        "Celaya",
        "Chitungwiza",
        "Corrientes",
        "Cuernavaca",
        "Cordoba",
        "Chanda",
        "Canoas",
        "Cabanatuan City",
        "Chongjin",
        "Corpus Christi",
        "Ciudad del Este",
        "Chimbote",
        "Cluj-Napoca",
        "Calamba",
        "Cherepovets",
        "Cusco",
        "Cabuyao",
        "Chita",
        "Chernihiv",
        "Chinju",
        "Ciudad Victoria",
        "Craiova",
        "Constanta",
        "Changyi",
        "Ciudad Obregon",
        "Cincinnati",
        "Cabimas",
        "Catania",
        "Cainta",
        "Coacalco",
        "Cuenca",
        "Cherkasy",
        "Caucaia",
        "Chernivtsi",
        "Chengzhong",
        "Chula Vista",
        "Chandler",
        "Changle",
        "Cascavel",
        "Chimoio",
        "Cirebon",
        "Cox's Bazar",
        "Carabanchel",
        "Colonia del Valle",
        "Czestochowa",
        "City of Westminster",
        "Chemnitz",
        "Coro",
        "Centurion",
        "Coatzacoalcos",
        "Chesapeake",
        "Caruaru",
        "Chigasaki",
        "Croix-des-Bouquets",
        "Ciudad Lineal",
        "Chi Linh",
        "Campeche",
        "Chon Buri",
        "Colombo",
        "Concepcion",
        "Centralniy",
        "Chofu",
        "Cartagena",
        "Chuncheon",
        "Chungju",
        "Ciputat",
        "Ciampea",
        "Corlu",
        "Cileungsir",
        "Chiniot",
        "Chapra",
        "Chiang Mai",
        "Columbus",
        "Charleroi",
        "Chakwama",
        "Changji",
        "Capiata",
        "Ciudad Madero",
        "Curug",
        "Cork",
        "Camacari",
        "Cibinong",
        "Chilpancingo",
        "Cachoeiro de Itapemirim",
        "Cienfuegos",
        "Cergy-Pontoise",
        "Corum",
        "Cua",
        "Carletonville",
        "Chandannagar",
        "Crawley",
        "Castello de la Plana",
        "Cotabato",
        "Chlef",
        "Ciudad Camilo Cienfuegos",
        "Chattanooga",
        "Cape Coral",
        "Cotia",
        "Cikupa",
        "Cuddalore",
        "Croydon",
        "Chicoloapan",
        "Carolina",
        "Chirchiq",
        "Ciudad del Carmen",
        "Chalco",
        "Calabozo",
        "Carupano",
        "Corona",
        "Criciuma",
        "Coquimbo",
        "Chapeco",
        "Cary",
        "Cambridge",
        "Centro Habana",
        "Ciudad Ojeda",
        "Cuautla",
        "Chincha Alta",
        "Cairns",
        "Chenghua",
        "Can Giuoc",
        "Ciudad Benito Juarez",
        "Chetumal",
        "Chillan",
        "Cagliari",
        "Clarksville",
        "Chingola",
        "Caxias",
        "Cam Ranh",
        "Chamberi",
        "Cikampek",
        "Concordia",
        "Cabo",
        "Calama",
        "Cape Coast",
        "Ciego de Avila",
        "Chertanovo Yuzhnoye",
        "Cordoba",
        "Comodoro Rivadavia",
        "Chamartin",
        "Coquitlam",
        "Choloma",
        "Clermont-Ferrand",
        "Chitradurga",
        "Chaohu",
        "Castanhal",
        "Colima",
        "Cam Pha Mines",
        "Cam Pha",
        "Cajamarca",
        "Chhindwara",
        "Cartago",
        "Ciudad Acuna",
        "Columbia",
        "Carrollton",
        "Charleston",
        "Cerro",
        "Cedar Rapids",
        "Cambridge",
        "Coral Springs",
        "Copiapo",
        "Charallave",
        "Cadiz",
        "Concord",
        "Cuddapah",
        "Cadiz",
        "Chinandega",
        "Ciudad Valles",
        "Ciamis",
        "Chishtian",
        "Colchester",
        "Carora",
        "Chikmagalur",
        "Chico",
        "Cachoeirinha",
        "Charlottenburg Bezirk",
        "Columbia",
        "Cagua",
        "Cubatao",
        "Ciudad Delicias",
        "Ciudad de Villa de Alvarez",
        "Cacak",
        "Co GJo",
        "Cheltenham",
        "Chenggu",
        "Cherkessk",
        "Cavite City",
        "Carlsbad",
        "Cuauhtemoc",
        "Cuito",
        "Chorzow",
        "Costa Mesa",
        "Chesterfield",
        "Clearwater",
        "Chanduasi",
        "Chas",
        "Ca Mau",
        "Conselheiro Lafaiete",
        "Chhatarpur",
        "Chelmsford",
        "Cileunyi",
        "Caen",
        "Cambridge",
        "Citeureup",
        "Centennial",
        "Corona",
        "Catanduva",
        "Cuautitlan",
        "Cabo Frio",
        "College Station",
        "Catia La Mar",
        "Chittaurgarh",
        "Cheremushki",
        "Coimbra",
        "Cikarang",
        "Chengtangcun",
        "Clovis",
        "Churu",
        "Cabudare",
        "Curico",
        "Concepcion de La Vega",
        "Ciutat Vella",
        "Chakwal",
        "Colatina",
        "Coronel Fabriciano",
        "Chinatown",
        "Chikushino-shi",
        "Colonia Lindavista",
        "Chanthaburi",
        "Clinton Township",
        "Columbia",
        "Cardenas",
        "Compton",
        "Chengzihe",
        "Ciudad Guzman",
        "Comitan",
        "Chinautla",
        "Corumba",
        "Chalisgaon",
        "Ceyhan",
        "Ceske Budejovice",
        "Ciudad Rio Bravo",
        "Charsadda",
        "Campo Largo",
        "Chilakalurupet",
        "Cacem",
        "Closepet",
        "Carson",
        "Changping",
        "Caceres",
        "Chitose",
        "Coronel",
        "Caringin",
        "Calumpit",
        "Cardenas",
        "Cambe",
        "Chauk",
        "Caraguatatuba",
        "Chester",
        "Coslada",
        "Chinatown",
        "Chengxiang",
        "Cicurug",
        "Crato",
        "Carmel",
        "Contai",
        "Chosica",
        "Chaman",
        "Cienaga",
        "Cholula",
        "Canakkale",
        "Concord",
        "Canarsie",
        "Caieiras",
        "Cornella de Llobregat",
        "Citrus Heights",
        "Chirala",
        "Canton",
        "Caguas",
        "Chaykovskiy",
        "Clifton",
        "Cai Rang",
        "Cannock",
        "Champaign",
        "Chipata",
        "Chino",
        "Courbevoie",
        "Creteil",
        "Ciudad Mante",
        "Cottbus",
        "Cerkezkoey",
        "Curepipe",
        "Cicero",
        "Codo",
        "Chervonohrad",
        "Chichawatni",
        "Changqing",
        "Chiguayante",
        "Cukai",
        "Chimaltenango",
        "Colombes",
        "Como",
        "Campana",
        "Changning",
        "Cranston",
        "Cizre",
        "Cung Kiem",
        "Cruzeiro do Sul",
        "Chichicastenango",
        "Ciudad Lerdo",
        "Cesena",
        "Ciudad Lazaro Cardenas",
        "Chaigou",
        "Catanzaro",
        "Cerro de Pasco",
        "Chiang Rai",
        "Ceuta",
        "Carlisle",
        "Chino Hills",
        "Castrop-Rauxel",
        "Ciranjang-hilir",
        "Chiclana de la Frontera",
        "Cozumel",
        "Coyah",
        "Chilliwack",
        "Champigny-sur-Marne",
        "Colon",
        "Ciudad Satelite",
        "Camden",
        "Ciudad Choluteca",
        "Chekhov",
        "Crewe",
        "Chatham",
        "Campo Mourao",
        "Chaoyang",
        "Cheektowaga",
        "Cipolletti",
        "Cu Chi",
        "Cachoeira do Sul",
        "Changnyeong",
        "Calais",
        "Ciudad Real",
        "Chimbas",
        "Chandpur",
        "Canary Wharf",
        "Chilca",
        "Cuamba",
        "Caserta",
        "Cacapava",
        "Cheria",
        "Capas",
        "Cruzeiro",
        "Caidian",
        "Canton",
        "Chintamani",
        "Chelghoum el Aid",
        "Chernogorsk",
        "Cankiri",
        "Changtu",
        "Centreville",
        "Cinisello Balsamo",
        "Celle",
        "Carpina",
        "Cherry Hill",
        "Contramaestre",
        "Chivacoa",
        "Chau Doc",
        "Chapayevsk",
        "Cannes",
        "Chenab Nagar",
        "Consolacion del Sur",
        "Chalus",
        "Chengxian Chengguanzhen",
        "Chuchar-kana Mandi",
        "Cantaura",
        "Chulucanas",
        "Conroe",
        "Chinchina",
        "Cabo San Lucas",
        "Cadereyta Jimenez",
        "Catbalogan",
        "Cadereyta",
        "Chamrajnagar",
        "Chaihe",
        "Calbayog City",
        "Campina",
        "Concepcion del Uruguay",
        "Camarillo",
        "Chaguanas",
        "Caohe",
        "City of Isabela",
        "Caicara del Orinoco",
        "Chiryu",
        "Casas Adobes",
        "Channapatna",
        "Chengyang",
        "Caledon",
        "Chaibasa",
        "Chingford",
        "Cabinda",
        "Calapan",
        "Cedar Park",
        "Castellammare di Stabia",
        "Chengalpattu",
        "Chopda",
        "Caldas",
        "Colmar",
        "Cruz Alta",
        "Capelle aan den IJssel",
        "Caoqiao",
        "Cricklewood",
        "Conway",
        "Chust",
        "Cair",
        "Chacao",
        "Chia",
        "Changli",
        "Concepcion",
        "Chinnachowk",
        "Curvelo",
        "Chelm",
        "Cyangugu",
        "Colon",
        "Cosenza",
        "Cao Lanh",
        "Cacador",
        "Chokwe",
        "Caldas Novas",
        "Catalao",
        "Cheyenne",
        "Changcheng",
        "Collado-Villalba",
        "Carol City",
        "Changle",
        "Cataguases",
        "Cubuk",
        "Council Bluffs",
        "Colon",
        "Coon Rapids",
        "Chistopol'",
        "Calarca",
        "Castelldefels",
        "Carmichael",
        "Chinhoyi",
        "Cortazar",
        "Chambery",
        "Cayenne",
        "Castro Valley",
        "Chinch'on",
        "Candelaria",
        "Cumbum",
        "Canoga Park",
        "Cupertino",
        "Ciudad Hidalgo",
        "Castleford",
        "Casper",
        "Caratinga",
        "Chelsea",
        "Coney Island",
        "Colonia Nativitas",
        "Chapel Hill",
        "Cremona",
        "Canyon Country",
        "Carazinho",
        "Coconut Creek",
        "Craigavon",
        "Chibuto",
        "Chalkida",
        "Comayagua",
        "Cerdanyola del Valles",
        "Carrara",
        "Chidambaram",
        "Chornomors'k",
        "Chichibu",
        "Casoria",
        "Chonglong",
        "Chaiyaphum",
        "Clay",
        "Central City",
        "Caucasia",
        "Cogan",
        "Chik Ballapur",
        "Cergy",
        "Clichy",
        "Cheremkhovo",
        "Cheshunt",
        "Chililabombwe",
        "Chunian",
        "Catacaos",
        "Center City",
        "Chhibramau",
        "Colegiales",
        "Corby",
        "Chicopee",
        "Caltanissetta",
        "Cajamar",
        "Castlereagh",
        "Chino",
        "Changleng",
        "Chernaya Rechka",
        "Cianorte",
        "Carmona",
        "Cuenca",
        "Changling",
        "Chumphon",
        "Corvallis",
        "Castle Rock",
        "Cacoal",
        "Chicago Lawn",
        "Cerete",
        "Concordia",
        "Canterbury",
        "Can Gio",
        "Cepu",
        "Cypress Hills",
        "Caico",
        "Cabedelo",
        "Caaguazu",
        "Colton",
        "Carson City",
        "Chivilcoy",
        "Cerignola",
        "Chania",
        "Cathedral City",
        "Chystyakove",
        "Commerce City",
        "Charikar",
        "Coatepec",
        "Challakere",
        "Coban",
        "Chaeryong-up",
        "Campos do Jordao",
        "Chateauroux",
        "Camaqua",
        "Cholet",
        "Ciudad de Huajuapan de Leon",
        "Carpi Centro",
        "Crateus",
        "Chikhli",
        "Cocorote",
        "Colcapirhua",
        "Cuxhaven",
        "Caucaguito",
        "Corroios",
        "Ciudad Bolivia",
        "Charleville-Mezieres",
        "Cascavel",
        "Crosby",
        "Ciudad Piar",
        "Corralillo",
        "Calvia",
        "Caldwell",
        "Cumbernauld",
        "Casa Grande",
        "Chiplun",
        "Changanacheri",
        "Clamart",
        "Coronel Oviedo",
        "City of Milford",
        "Chalons-en-Champagne",
        "Coral Gables",
        "Comal",
        "Catalina Foothills",
        "Charkhi Dadri",
        "Clacton-on-Sea",
        "Coari",
        "Carsamba",
        "Chomutov",
        "Chusovoy",
        "Craigieburn",
        "Ciudad Sandino"],

    "D": ["Delhi",
        "Dhaka",
        "Dongguan",
        "Dalian",
        "Durban",
        "Dubai",
        "Dar es Salaam",
        "Daegu",
        "Dakar",
        "Datong",
        "Daqing",
        "Dazhou",
        "Damascus",
        "Daejeon",
        "Douala",
        "Dallas",
        "Davao",
        "Depok",
        "Dhanbad",
        "Dombivli",
        "Donetsk",
        "Dublin",
        "Dongying",
        "Dnipro",
        "Da Nang",
        "Denpasar",
        "Duque de Caxias",
        "Dammam",
        "Deyang",
        "Denver",
        "Dezhou",
        "Dushanbe",
        "Detroit",
        "Diyarbakir",
        "Dandong",
        "Djibouti",
        "Dortmund",
        "Duesseldorf",
        "Dehra Dun",
        "Durgapur",
        "Duisburg",
        "Dresden",
        "Di An",
        "Dasmarinas",
        "Davangere",
        "Dingxi",
        "Diadema",
        "Delmas 73",
        "Dhulia",
        "Diepsloot",
        "Doha",
        "Denizli",
        "Dindigul",
        "Darbhanga",
        "Dengzhou",
        "Dihok",
        "Derby",
        "Donghai",
        "Dewas",
        "Durham",
        "Durg",
        "Dire Dawa",
        "Deir ez-Zor",
        "Djougou",
        "Dera Ghazi Khan",
        "Dali",
        "Dzerzhinsk",
        "Damanhur",
        "Diez de Octubre",
        "Dehiwala-Mount Lavinia",
        "Daloa",
        "Daliang",
        "Des Moines",
        "Dinajpur",
        "Debrecen",
        "Deoghar",
        "Dudley",
        "Duyun",
        "Da Lat",
        "Divinopolis",
        "Donaustadt",
        "Dunhuang",
        "Dodoma",
        "Dosquebradas",
        "Dongling",
        "Dagupan",
        "Dasoguz",
        "Deer Valley",
        "Dourados",
        "Delegacion Cuajimalpa de Morelos",
        "Dhamar",
        "Doncaster",
        "Djelfa",
        "Dinapore",
        "Dingzhou",
        "Dili",
        "Dijon",
        "Dunhua",
        "Dundee",
        "District of Taher",
        "Dumai",
        "Dayton",
        "Darmstadt",
        "Dadu",
        "Dikirnis",
        "Dawei",
        "Dese",
        "Dimapur",
        "Dimitrovgrad",
        "Dawukou",
        "Denton",
        "Dongyang",
        "Dehri",
        "Deoria",
        "Darwin",
        "Divo",
        "Daska Kalan",
        "Danshui",
        "Derince",
        "Darjiling",
        "Dos Hermanas",
        "Dam Dam",
        "Dibrugarh",
        "Durres",
        "Deoli",
        "Daito",
        "Dordrecht",
        "Damoh",
        "Dabrowa Gornicza",
        "Dasha",
        "Digos",
        "Dunedin",
        "Downey",
        "Dharmavaram",
        "Dumaguete",
        "Duma",
        "Daugavpils",
        "Dongtai",
        "Delicias",
        "Datun",
        "Didao",
        "Dehui",
        "Dharan",
        "Dagenham",
        "Daly City",
        "Derbent",
        "Daxing",
        "Douliu",
        "Depok",
        "Dolisie",
        "Davenport",
        "Dhaulpur",
        "Drobeta-Turnu Severin",
        "Disuq",
        "Delta",
        "Dera Ismail Khan",
        "Dartmouth",
        "Davie",
        "Dongsheng",
        "Dhahran",
        "Dukuhturi",
        "Dar'a",
        "Deventer",
        "Dschang",
        "Ducheng",
        "Dearborn",
        "Delft",
        "Dobrich",
        "Dogonbadan",
        "Dunhou",
        "Daotian",
        "Dipolog",
        "Dueren",
        "Dalai",
        "Darlington",
        "Dhangadhi",
        "Dongcun",
        "Disa",
        "Delmas",
        "Duitama",
        "Danjiangkou",
        "Drammen",
        "Datia",
        "Duobao",
        "Dongxing",
        "Deltona",
        "Deoband",
        "Deqing",
        "Dhamtari",
        "Duluth",
        "Dengzhou",
        "Dapitan",
        "Danbury",
        "Dacheng",
        "Daxi",
        "Dundee",
        "Dazhong",
        "Dongxia",
        "Dohad",
        "Degan",
        "Derry",
        "Dali Old Town",
        "Dhar",
        "David",
        "Donghe",
        "Dhoraji",
        "Dashiqiao",
        "Dushan",
        "Dorsten",
        "Deerfield Beach",
        "Drohobych",
        "Darnah",
        "Deurne",
        "Doddaballapura",
        "Dondo",
        "Daura",
        "Daet",
        "Daltonganj",
        "Damiao",
        "Dhulian",
        "Damietta",
        "Delmenhorst",
        "Doral",
        "Dhrangadhra",
        "Dakhla",
        "Dipalpur",
        "Darhan",
        "Detmold",
        "Decatur",
        "Dausa",
        "Dongdu",
        "Dachnoye",
        "Dongkan",
        "Dingcheng",
        "Dharapuram",
        "Darayya",
        "Delgado",
        "Donggongon",
        "Dunkerque",
        "Dadri",
        "Dazaifu",
        "Dinslaken",
        "Danao",
        "Dogubayazit",
        "Dainava (Kaunas)",
        "Dehdasht",
        "Dabou",
        "Dushanzi",
        "Denov",
        "Dothan",
        "Dolgoprudnyy",
        "Dorogomilovo",
        "Dovzhansk",
        "Dongfeng",
        "Deva",
        "Dayrut",
        "Dessau",
        "Damghan",
        "Davis",
        "Dimbokro",
        "Duoba",
        "Dambulla",
        "Dinalupihan",
        "Daxu",
        "Delray Beach",
        "Dharmapuri",
        "Dale City",
        "Dashitou",
        "Dar Kulayb",
        "Don Torcuato",
        "Daytona Beach",
        "Dengbu",
        "Dundalk",
        "Dormagen",
        "Darab",
        "Dhuburi",
        "Drancy",
        "Deqen",
        "Druzhkivka",
        "Dhenkanal",
        "Dabwali",
        "Daye",
        "Dmitrov",
        "Dongning",
        "Datong",
        "Dabra",
        "Dubna",
        "Dingjia",
        "Douane",
        "Dazeshan",
        "Debre Mark'os",
        "Den Helder",
        "Dayr al Balah",
        "Drummondville",
        "Dolores Hidalgo Cuna de la Independencia Nacional",
        "Dubuque",
        "Des Plaines",
        "Dingtao",
        "Debre Birhan",
        "Duezce",
        "Dublin",
        "Diphu",
        "Diamond Bar",
        "Dartford",
        "Dewsbury",
        "Daokou",
        "Doertyol",
        "Dabhoi",
        "Dearborn Heights",
        "Dalianwan",
        "Dakhla",
        "Decatur",
        "Dorbod",
        "Drean",
        "Dholka",
        "Dhuri",
        "Dishna",
        "Dar Chioukh",
        "Domodedovo",
        "Danane",
        "Deolali",
        "Djamaa",
        "Delano",
        "Dianbu",
        "Diglur",
        "Daxing",
        "DeSoto",
        "Dandeli",
        "Dapeng",
        "Decin",
        "Dunstable",
        "Dashahe",
        "Duzhou",
        "Diyarb Najm",
        "Dianzi",
        "Donetsk",
        "Dumraon",
        "Decan",
        "Dunfermline",
        "Djemmal",
        "Dunaujvaros"],

    "E": [
        "Ecatepec de Morelos",
        "Erbil",
        "Edmonton",
        "Enugu",
        "El Paso",
        "E'zhou",
        "Essen",
        "Ebute Ikorodu",
        "Erode",
        "Esenler",
        "Eskisehir",
        "East London",
        "Edinburgh",
        "East Jerusalem",
        "Erzurum",
        "El Obeid",
        "Elazig",
        "Ensenada",
        "Efon-Alaaye",
        "Enshi",
        "Eixample",
        "El Daein",
        "Etawah",
        "Espoo",
        "El Fasher",
        "Eimsbuettel",
        "Elche",
        "El Tigre",
        "Embu",
        "Eldoret",
        "Esenyurt",
        "Eindhoven",
        "Erfurt",
        "Edea",
        "Engels",
        "Ezhou",
        "Ellore",
        "East Flatbush",
        "East New York",
        "Ech Chettia",
        "Eloy Alfaro",
        "Elk Grove",
        "Esmeraldas",
        "Eugene",
        "Envigado",
        "El Achir",
        "East Chattanooga",
        "Enschede",
        "Escondido",
        "El Limon",
        "East Hampton",
        "El Jadid",
        "Elektrostal'",
        "eMbalenhle",
        "Ejigbo",
        "El Oued",
        "Ebetsu",
        "Elizabeth",
        "El Eulma",
        "Elblag",
        "East Los Angeles",
        "Edirne",
        "Epworth",
        "Ekibastuz",
        "Ejido",
        "Evansville",
        "Eastbourne",
        "Exeter",
        "El Monte",
        "East Harlem",
        "Eunapolis",
        "Erzincan",
        "Elmhurst",
        "Elgin",
        "Esuk Oron",
        "Encheng",
        "East Independence",
        "El Vigia",
        "Enterprise",
        "Everett",
        "Elista",
        "Enfield Town",
        "Ed Damer",
        "El Cajon",
        "Esmeraldas",
        "Escuintla",
        "Erlangen",
        "Edison",
        "Elbasan",
        "El Progreso",
        "Erie",
        "Esteli",
        "Erechim",
        "Esslingen",
        "Errachidia",
        "Eregli",
        "Ercis",
        "Emure-Ekiti",
        "Edmond",
        "Eregli",
        "El Puerto de Santa Maria",
        "Ebolowa",
        "Enchanted Hills",
        "Effium",
        "Esteio",
        "Epe",
        "El Ejido",
        "Eisen",
        "East Norwalk",
        "Edinburg",
        "El Khroub",
        "Edmonton",
        "Emmiganur",
        "Elbistan",
        "El Cafetal",
        "Erdenet",
        "Ende",
        "Embu Guacu",
        "Evanston",
        "Encarnacion",
        "El Tocuyo",
        "East Kilbride",
        "El Hamma",
        "Esbjerg",
        "El Pueblito",
        "Ejura",
        "Eha Amufu",
        "Essaouira",
        "Enugu-Ukwu",
        "Es Senia",
        "Eau Claire",
        "Ellesmere Port",
        "Ede",
        "Ezza-Ohu",
        "Eskilstuna",
        "Eagan",
        "Ellicott City",
        "Estepona",
        "East Orange",
        "El Bayadh",
        "Eden Prairie",
        "El Prat de Llobregat",
        "Entebbe",
        "Encinitas",
        "East Village",
        "Erd",
        "Erzsebetvaros",
        "Eiguliai",
        "Erdaojiang",
        "Esfarayen",
        "Ekpoma",
        "Eastvale",
        "Evreux",
        "Emin",
        "El Hatillo",
        "Emmen",
        "Eger",
        "Espinal",
        "Eisen",
        "Ezhva",
        "Eschweiler",
        "Elk",
        "Estancia",
        "Evora",
        "Eminoenue",
        "Etawa",
        "Elda",
        "Euskirchen",
        "Edgewater",
        "Encanto",
        "El Banco",
        "Eastleigh",
        "Euless",
        "East Pensacola Heights",
        "Elyria",
        "Ercolano",
        "El Viejo",
        "Enerhodar",
        "Ergani",
        "Esher",
        "Elkhart",
        "Eilat",
        "Erbaa",
        "Evry",
        "Enid",
        "Emden",
        "East Hartford",
        "Erftstadt",
        "Edina"],

    'F': [
        "Foshan",
        "Fuzhou",
        "Faisalabad",
        "Fortaleza",
        "Fuyang",
        "Fushun",
        "Fukuoka",
        "Faridabad",
        "Fuzhou",
        "Fes",
        "Fort Worth",
        "Freetown",
        "Fuxin",
        "Frankfurt am Main",
        "Feira de Santana",
        "Fresno",
        "Florianopolis",
        "Fujisawa",
        "Fukuyama",
        "Fenghuang",
        "Florence",
        "Firozabad",
        "Franca",
        "Fukushima",
        "Foz do Iguacu",
        "Fangchenggang",
        "Fort Wayne",
        "Floridablanca",
        "Fukui-shi",
        "Farrukhabad",
        "Fuji",
        "Fremont",
        "Fendou",
        "Formosa",
        "Fuencarral-El Pardo",
        "Freiburg",
        "Fontana",
        "Fayetteville",
        "Favoriten",
        "Fuenlabrada",
        "Fuding",
        "Fort Lauderdale",
        "Fengcheng",
        "Francisco Morato",
        "Ferraz de Vasconcelos",
        "Fianarantsoa",
        "Fuling",
        "Fatehpur",
        "Fergana",
        "Floridsdorf",
        "Fengcheng",
        "Fort Collins",
        "Fes al Bali",
        "Fu'an",
        "Frisco",
        "Fyzabad",
        "Fullerton",
        "Fuyu",
        "Foggia",
        "Funtua",
        "Fujieda",
        "Fujinomiya",
        "Fuji",
        "Florencia",
        "Fresnillo",
        "Fengcheng",
        "Fernando de la Mora",
        "Fargo",
        "Friedrichshain Bezirk",
        "Fairfield",
        "Faridpur",
        "Furth",
        "Franco da Rocha",
        "Fukayacho",
        "Ferozepore",
        "Funchal",
        "Flint",
        "Fasa",
        "Fangshan",
        "Federal Way",
        "Frederiksberg",
        "Fordham",
        "Facatativa",
        "Fall River",
        "Fangcheng Chengguanzhen",
        "Forli",
        "Flatbush",
        "Ferrara",
        "Foumban",
        "Fort-de-France",
        "Francistown",
        "Fujin",
        "Fusagasuga",
        "Fukuroi",
        "Fort Smith",
        "Fulham",
        "Flensburg",
        "Foumbot",
        "Feni",
        "Fatehpur",
        "Fayetteville",
        "Fatsa",
        "Farmington Hills",
        "Formosa",
        "Feicheng",
        "Fili",
        "Feicheng",
        "Faridkot",
        "Focsani",
        "Fishers",
        "Fenghua",
        "Fuorigrotta",
        "Fylde",
        "Folsom",
        "Furukawa",
        "Fuyu",
        "Ferrol",
        "Fuentes del Valle",
        "Fort Myers",
        "Fredrikstad",
        "Franklin",
        "Finlyandskiy",
        "Faridpur",
        "Fuengirola",
        "Fiditi",
        "Flower Mound",
        "Fazilka",
        "Flagstaff",
        "Fuyang",
        "Fordon",
        "Fengping",
        "Frederick",
        "Frontera",
        "Fukuchiyama",
        "Feodosiya",
        "Framingham",
        "Forest Hills",
        "Fuqing",
        "Fengkou",
        "Fort McMurray",
        "Firuzabad",
        "Folkestone",
        "Fatehabad",
        "Finchley",
        "Framingham Center",
        "Fengrun",
        "Fenggang",
        "Fulda",
        "Flatlands",
        "Florence-Graham",
        "Fujioka",
        "Frenda",
        "Fuwwah",
        "Florida",
        "Fanlou",
        "Faqus",
        "Fochville",
        "Ferkessedougou",
        "Fernandopolis",
        "Fengyi",
        "Fier-Cifci",
        "Financial District",
        "Fethiye",
        "Farnborough",
        "Fountainebleau",
        "Ferizaj",
        "Frydek-Mistek",
        "Fundacion",
        "Fairfield",
        "Fenyi",
        "Fort Beaufort",
        "Friedrichshafen",
        "Faraskur",
        "Felgueiras",
        "Farroupilha",
        "Francisco Beltrao",
        "Fareham",
        "Frankfurt (Oder)",
        "Fountain Valley",
        "Fussa",
        "Formiga",
        "Fier",
        "Forest",
        "Funza",
        "Fangcun",
        "Farshut",
        "Fnidek",
        "Fryazevo",
        "Frejus",
        "Fredericton",
        "Florissant",
        "Fryazino",
        "Fontenay-sous-Bois",
        "Futtsu",
        "Fastiv",
        "Flagami",
        "Fuchucho"
    ]

}